[package]
name = "sic_xe_simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
timer = "0.2.0"
color-eyre = "0.6.5"
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.31"
ratatui = "0.29.0"
tokio = { version = "1.40.0", features = ["full"] }
